### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by afg137** [mossblaser/signal_for_android_decryption#8]
Getting the error "google.protobuf.message.DecodeError: Error parsing message" in line 152 in `decrypt_frame` (`return BackupFrame.FromString(frame_bytes)`) when trying to decrypt a backup.

The backup was generated a few weeks ago, using the latest version of Signal at the time.

This seems strange, since your [Backups.proto](https://github.com/mossblaser/signal_for_android_decryption/blob/main/Backups.proto) file since to be the same one as [Signal's](https://github.com/signalapp/Signal-Android/blob/03845eabaf1a864ec9011a70d3304dfda46af403/app/src/main/protowire/Backups.proto#L11), so not sure why there is a decoding error.

Any help would be very appreciated. Thanks!

**Comment by mossblaser** [comment]
Uh-oh! Sounds like something in the serialisation format they're using has changed :/. If you're getting to that point (rather than getting a HMAC error) then it sounds like all the obvious stuff like incorrect keys or changes in cryptography can be ruled out.

Unfortunately I don't really have any suggestions on where to go next with this besides take a look at where in the bitstream you're hitting that error (e.g. which type of frame you've got, how far through the file it is, etc.) and digging into the signal sources.

Sorry to not be of much help, though I'd be delighted to accept any PRs if you find out what's going on!

**Comment by afg137** [comment]
Seems like the error is in the first frame; adding a print statement right before line 152 results in only one loop. Is there anything special about this frame?

**Comment by mossblaser** [comment]
I don't think so! :/ Hmm.

**Comment by mossblaser** [comment]
I've just attempted to decrypt a freshly generated backup by a recent version of Signal and it seems I don't run into this problem.

I'll leave this issue open in case anyone else runs into the same thing, though!

Have you had any luck getting this to work? Perhaps it would be worth trying again with a fresh backup file?

**Comment by mossblaser** [comment]
Closing this for now as I can't reproduce the issue and I've not heard any more. Please re-open if you manage to make any further headway!

**Comment by ssskhan** [comment]
Hi, I’m encountering the same issue on the latest version of Signal. Below are the details of my setup and the traceback for your reference:

**Environment:**
- Operating System: Windows 10
- Python Version: 3.8.0
- Signal Version: 7.27.1 (backup generated on 18/12/2024)

**Traceback:**
```plaintext
Traceback (most recent call last):
  File "D:\python\signal_for_android_decryption\decrypt_backup.py", line 426, in <module>
    main()
  File "D:\python\signal_for_android_decryption\decrypt_backup.py", line 413, in main
    for _ in decrypt_backup(
  File "D:\python\signal_for_android_decryption\decrypt_backup.py", line 270, in decrypt_backup
    backup_frame = decrypt_frame(
  File "D:\python\signal_for_android_decryption\decrypt_backup.py", line 153, in decrypt_frame
    return BackupFrame.FromString(frame_bytes)
google.protobuf.message.DecodeError: Error parsing message

**Comment by mossblaser** [comment]
This is very curious. It seems like this may be a problem related to running this script under Windows :/ #10 seems to describe a similar issue with everything "just working" under Linux.

It might also be worth trying it under a more recent Python release: 3.8 is now EOL and its possible that something somewhere has silently dropped support.

I'd be very interested to hear how you get on trying either a more recent Python or, failing that, a non-Windows OS (if possible!). If you're up for it and fancy trying to work out exactly where things diverge we might be in with a chance of fixing/working around whatever is going on! Unfortunately I don't have access to a Windows machine to try it myself!

Please let me know how you get along; I'll reopen the issue whilst you're looking into this! Thanks for your help!

---

Just to verify I've just successfully run the script against a backup created today (19/12/2024), also with the same Signal version so it feels most likely this is an environment issue. (It could always be a "your data uses a feature mine doesn't" situation but those kind of issues seem to usually manifest much later).

**Comment by ssskhan** [comment]
I just created the account a couple of days ago, there is no one in contacts, created a group with only me as the member and send a couple of messages to the group, the sole purpose of creating the account was to check the decryption of signal backup.

 Tried on `py 3.9.13` but same issue,  what is your python version be the way ?
 
 UPDATE: Tried on linux same issue,
 
 Environment:
- Operating System: Ubuntu 22.04.2 LTS
- Python Version: 3.10.12



UPDATE: I thought there might be issue related to no real chat in the backup so I sent a couple of messages to a contact but still same issue. ( tried this new backup file on windows tho )

**Comment by mossblaser** [comment]
Hmm... well that's very interesting :/. I think the next things to try would be to print some messages as it proceeds through the file to see at what point it hits this problem and start digging!

**Comment by ssskhan** [comment]
getting this on first iteration so sadly cant print any messages

**Comment by mossblaser** [comment]
That's thoroughly puzzling: the blob of data which is failing to unpack is also validated by the HMAC so presumably we're not failing to chop the file up :/.

Have you tried looking at the decrypted binary which the protobuf is failing to parse? Perhaps with a little knowledge of the protobuf format you might be able to work out what's going wrong.

It is odd though; the protobuf spec doesn't appear to have changed.

**Comment by Hildegard49** [comment]
I ran into the same issue when i passed the wrong passphrase. If the decrypted frame length happen to be greater than the actual file length, the MAC verification does not fail although the wrong passphrase was given. 

`if their_mac != our_mac[: len(their_mac)]:
             raise MACMismatchError()`

`their_mac` and `our_mac` are two empty strings then as `len(their_mac) = 0`. And the protobuf parsing error is raised. 

This can be fixed if `len(their_mac)` is hardcoded `our_mac[: 10]`

**Comment by mossblaser** [comment]
Great sleuthing!

And as for my part in this bug, I genuinely can't account for why I wouldn't have hard coded the length (I do on the read length after all!). If this were in something more important I'd almost be suspecting a deliberate sabotage it's such a bizarre bug! Alas, the simpler likely explanation was that I wrote that code with a very small baby in my life!

Unfortunately I'm away from an editior at the moment so it'll be a day or two before I can supply the obvious patch!

**Comment by mossblaser** [comment]
Thanks again, @Hildegard49; I've pushed up the fix and I hope you don't mind being added to the list of contributors given how long this bug has sat unsolved!

To those following along at home: the issues seen above are almost certainly down to a bad passphrase being misreported as a protobuf decoding error. The fix applied above should result in a more appropriate error being reported!
